# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-09 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u79f0')),
                ('singer', models.CharField(max_length=50, verbose_name='\u6b4c\u624b')),
                ('duration', models.IntegerField(default=0, verbose_name='\u65f6\u957f')),
                ('album', models.CharField(max_length=100, verbose_name='\u4e13\u8f91')),
            ],
            options={
                'verbose_name': '\u6b4c\u66f2',
                'verbose_name_plural': '\u6b4c\u66f2',
            },
        ),
    ]
