# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-09 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='url',
            field=models.CharField(default='', max_length=1000, verbose_name='url'),
            preserve_default=False,
        ),
    ]
