# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-15 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_scraper', '0025_new_follow_pages_page_xpath_pagination_attribute'),
        ('music', '0003_auto_20181214_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMusic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u79f0')),
                ('singer', models.CharField(max_length=50, verbose_name='\u6b4c\u624b')),
                ('duration', models.IntegerField(default=0, verbose_name='\u65f6\u957f')),
                ('album', models.CharField(max_length=100, verbose_name='\u4e13\u8f91')),
                ('url', models.CharField(max_length=1000, verbose_name='url')),
                ('checker_runtime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamic_scraper.SchedulerRuntime')),
            ],
        ),
        migrations.RenameModel(
            old_name='NewsWebsite',
            new_name='MusicsWebsite',
        ),
        migrations.RemoveField(
            model_name='article',
            name='checker_runtime',
        ),
        migrations.RemoveField(
            model_name='article',
            name='news_website',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AddField(
            model_name='cmusic',
            name='news_website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.MusicsWebsite'),
        ),
    ]
