# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OssFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.IntegerField(choices=[(0, 'dev'), (1, 'beta'), (2, 'demo'), (3, 'prod')], default=0, verbose_name='\u73af\u5883')),
                ('system', models.CharField(max_length=20, verbose_name='\u6765\u6e90\u7cfb\u7edf')),
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u79f0')),
                ('size', models.CharField(max_length=50, verbose_name='\u5927\u5c0f')),
                ('type', models.CharField(max_length=100, verbose_name='\u7c7b\u578b')),
                ('key', models.CharField(max_length=500, verbose_name='key')),
                ('fid', models.CharField(max_length=40, verbose_name='fid')),
                ('uploader_id', models.CharField(max_length=20, verbose_name='\u4e0a\u4f20\u7528\u6237ID')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='\u4e0a\u4f20\u65f6\u95f4')),
                ('upload_ip', models.CharField(max_length=40, verbose_name='\u4e0a\u4f20ip')),
            ],
            options={
                'verbose_name': 'oss\u6587\u4ef6',
                'verbose_name_plural': 'oss\u6587\u4ef6',
            },
        ),
    ]
