# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 04:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupExtension',
            fields=[
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='extension', serialize=False, to='auth.Group', verbose_name='\u7ec4')),
                ('group_type', models.IntegerField(choices=[(0, '\u62e5\u6709\u8005'), (1, '\u7ba1\u7406\u8005'), (2, '\u6210\u5458')], verbose_name='\u5206\u7ec4\u7c7b\u578b')),
                ('crt', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('upt', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='\u4f1a\u5458')),
                ('gender', models.CharField(max_length=1, verbose_name='\u6027\u522b')),
                ('mobile', models.CharField(max_length=20, verbose_name='\u624b\u673a')),
                ('wx_open_id', models.CharField(max_length=30, verbose_name='wx_open_id')),
                ('wx_union_id', models.CharField(blank=True, max_length=30, verbose_name='wx_union_id')),
                ('crt', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('upt', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u79f0')),
                ('alias', models.CharField(blank=True, max_length=50, verbose_name='\u522b\u540d')),
                ('crt', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('upt', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
            ],
        ),
    ]
