# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180606_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u53d1\u5e03'),
        ),
    ]
