# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pv',
            field=models.IntegerField(default=0, verbose_name='pv'),
        ),
        migrations.AddField(
            model_name='article',
            name='uv',
            field=models.IntegerField(default=0, verbose_name='uv'),
        ),
    ]
