# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-01 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181105_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_spread',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u63a8\u5e7f'),
        ),
    ]
