# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crt', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('upt', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('cover', models.CharField(max_length=250, null=True, verbose_name='\u5c01\u9762')),
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u79f0')),
                ('intro', models.TextField(max_length=1000, null=True, verbose_name='\u7b80\u4ecb')),
                ('author', models.CharField(max_length=50, null=True, verbose_name='\u4f5c\u8005')),
                ('type', models.IntegerField(default=0, verbose_name='\u7c7b\u578b')),
            ],
            options={
                'verbose_name': '\u6f2b\u753b',
                'verbose_name_plural': '\u6f2b\u753b',
            },
        ),
        migrations.CreateModel(
            name='ComicSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crt', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('upt', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('origin', models.IntegerField(null=True, verbose_name='\u6e90')),
                ('season', models.IntegerField(null=True, verbose_name='\u5b63')),
                ('part', models.IntegerField(verbose_name='\u96c6')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic.Comic', verbose_name='\u6f2b\u753b')),
            ],
            options={
                'verbose_name': '\u6f2b\u753b\u8d44\u6e90',
                'verbose_name_plural': '\u6f2b\u753b\u8d44\u6e90',
            },
        ),
    ]
