# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crt', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('upt', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u65b0\u65f6\u95f4')),
                ('chapter', models.IntegerField(verbose_name='\u7ae0\u8282')),
                ('imgs', models.TextField(max_length=2000, verbose_name='\u56fe\u7247')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comic.Comic', verbose_name='\u6f2b\u753b')),
            ],
            options={
                'verbose_name': '\u6f2b\u753b\u8d44\u6e90',
                'verbose_name_plural': '\u6f2b\u753b\u8d44\u6e90',
            },
        ),
        migrations.RemoveField(
            model_name='comicsource',
            name='comic',
        ),
        migrations.DeleteModel(
            name='ComicSource',
        ),
    ]
