# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-03 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0002_auto_20181203_0610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comicchapter',
            options={'verbose_name': '\u6f2b\u753b\u7ae0\u8282', 'verbose_name_plural': '\u6f2b\u753b\u7ae0\u8282'},
        ),
        migrations.AddField(
            model_name='comic',
            name='ac_id',
            field=models.CharField(default='', max_length=100, verbose_name='ac_id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comicchapter',
            name='ac_id',
            field=models.CharField(default='', max_length=100, verbose_name='ac_id'),
            preserve_default=False,
        ),
    ]
