# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0003_auto_20181203_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comicchapter',
            name='ac_id',
        ),
        migrations.AddField(
            model_name='comicchapter',
            name='ac_cid',
            field=models.CharField(default='', max_length=100, verbose_name='ac_cid'),
            preserve_default=False,
        ),
    ]
