# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0005_auto_20181206_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicchapter',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='\u6807\u9898'),
            preserve_default=False,
        ),
    ]
