# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-15 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPerform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_intake', models.IntegerField(verbose_name='\u5403\u5976\u91cf')),
                ('is_shit', models.BooleanField(default=True, verbose_name='\u662f\u5426\u62c9\u5c4e')),
                ('shit_size', models.CharField(max_length=50, verbose_name='\u5c4e\u91cf')),
                ('shit_color', models.CharField(max_length=50, verbose_name='\u5c4e\u989c\u8272')),
                ('is_urinate', models.BooleanField(default=True, verbose_name='\u662f\u5426\u62c9\u5c3f')),
                ('urinate_size', models.CharField(max_length=50, verbose_name='\u5c3f\u91cf')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='\u6d3b\u52a8\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u65e5\u5e38\u8868\u73b0',
                'verbose_name_plural': '\u65e5\u5e38\u8868\u73b0',
            },
        ),
    ]
