# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-18 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby_daily', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyperform',
            name='shit_color',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u5c4e\u989c\u8272'),
        ),
        migrations.AlterField(
            model_name='dailyperform',
            name='shit_size',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u5c4e\u91cf'),
        ),
        migrations.AlterField(
            model_name='dailyperform',
            name='urinate_size',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u5c3f\u91cf'),
        ),
    ]
