# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-05 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u6e38\u620f',
                'verbose_name_plural': '\u6e38\u620f',
            },
        ),
    ]
